repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=5120"] # 5 MB
      - id: no-commit-to-branch
        args: [--branch, main]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
      - id: interrogate
        exclude: ^notebooks/|^tests/
        args: [-v, -i, --fail-under=80]
  - repo: https://github.com/mwouts/jupytext
    rev: v1.16.3
    hooks:
      - id: jupytext
        args: [--from, ipynb, --to, "py:light", --sync, --pipe, black]
        additional_dependencies:
          - black==24.4.2
