services:
  postgres:
    image: postgres:16.3
    restart: unless-stopped
    container_name: praice_db_cnt
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - praice_network

  inference_api:
    build:
      context: ./inference_api
      dockerfile: Dockerfile
    restart: unless-stopped
    image: praice_inference_api
    container_name: praice_inference_api_cnt
    ports:
      - 8001:8001
    volumes:
      - ~/.cache/huggingface/hub:/root/.cache/huggingface/hub
    networks:
      - praice_network

  redis:
    image: redis:7
    restart: unless-stopped
    container_name: redis_cnt
    ports:
      - 6379:6379
    networks:
      - praice_network

  celery:
    build:
      context: ./praice
      dockerfile: celery.Dockerfile
    restart: unless-stopped
    image: praice_celery
    container_name: praice_celery_cnt
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    command: >
      sh -c "
        celery -A praice.jobs.celery_config:app worker --loglevel=info &
        celery -A praice.jobs.celery_config:app beat --loglevel=info &
        wait
      "
    depends_on:
      - redis
      - inference_api
      - postgres
    networks:
      - praice_network

networks:
  praice_network:
    name: praice_network

volumes:
  postgres_data:
    name: praice_postgres_data
