services:
  scheduler:
    build:
      context: .
      dockerfile: ./scheduler.Dockerfile
    restart: unless-stopped
    image: praice_scheduler
    container_name: praice_scheduler_cnt
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs

  inference_api:
    build:
      context: ./inference_api
      dockerfile: Dockerfile
    restart: unless-stopped
    image: praice_inference_api
    container_name: praice_inference_api_cnt
    ports:
      - "8001:8001"
    volumes:
      - ~/.cache/huggingface/hub:/root/.cache/huggingface/hub