[project]
name = "praice"
version = "0.1.3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,< 3.12"
dependencies = [
    "anthropic==0.34.2",
    "beautifulsoup4==4.12.3",
    "celery==5.4.0",
    "loguru==0.7.2",
    "numpy==1.26.4",
    "openai==1.43.0",
    "pandas==2.2.2",
    "peewee==3.17.6",
    "psycopg2-binary==2.9.9",
    "pydantic-settings==2.4.0",
    "pydantic==2.8.2",
    "pytz==2024.1",
    "redis==5.0.8",
    "requests==2.32.3",
    "rich==13.7.1",
    "TA-Lib==0.6.3",
    "tqdm==4.66.5",
    "typer==0.12.3",
    "yfinance==0.2.41",
    "crewai[tools]>=0.95.0",
]
