runs:
  - model: flaml
    settings:
      - estimator_list:
          - lgbm
          - rf
          - xgboost
          - extra_tree
          - xgb_limitdepth
          - catboost
        time_budget: 180
        ensemble: false
        early_stop: true
  - model: tpot
    settings:
      - generations: 5
        population_size: 10
      - generations: 5
        population_size: 100
      - generations: 10
        population_size: 50
