runs:
  - model: flaml
    settings:
      - estimator_list:
          - lgbm
          - rf
          - xgboost
          - extra_tree
        time_budget: 60
        ensemble: false
        early_stop: true
      - estimator_list:
          - lgbm
          - rf
          - xgboost
          - extra_tree
          - xgb_limitdepth
          - catboost
        time_budget: 120
        ensemble: false
        early_stop: true
  - model: tpot
    settings:
      - generations: 3
        population_size: 200
      - generations: 6
        population_size: 100
