data:
  - period: 3y
    add_ta_indicators: true
    ta_indicators_config_fn: all_default
    add_date_features: true
    lookback_period: 0
    add_past_close_prices: false
    add_past_pct_changes: false
    forecast_period: 1
    train_size: 0.95
    val_size: 0.05
    test_size: 0.0
    separate_y: true
    dropna: true
    environment: research
  - period: 3y
    add_ta_indicators: true
    ta_indicators_config_fn: ema1
    add_date_features: true
    lookback_period: 2
    add_past_close_prices: false
    add_past_pct_changes: true
    forecast_period: 1
    train_size: 0.95
    val_size: 0.05
    test_size: 0.0
    separate_y: true
    dropna: true
    environment: research
  - period: 4y
    add_ta_indicators: false
    ta_indicators_config_fn: ""
    add_date_features: false
    lookback_period: 5
    add_past_close_prices: false
    add_past_pct_changes: true
    forecast_period: 1
    train_size: 0.95
    val_size: 0.05
    test_size: 0.0
    separate_y: true
    dropna: true
    environment: research
