# All available technical analysis indicators in
# TechnicalAnalysis class with default parameter values
indicators:
  moving_average:
    - ma_type: SMA
      period: 30
      source: close
    - ma_type: EMA
      period: 30
      source: close
    - ma_type: WMA
      period: 30
      source: close
    - ma_type: DEMA
      period: 30
      source: close
    - ma_type: KAMA
      period: 30
      source: close
    - ma_type: TRIMA
      period: 30
      source: close
  bollinger_bands:
    - period: 20
      std_dev: 2
      source: close
  momentum:
    - indicator: ADX
      period: 14
    - indicator: ADXR
      period: 14
    - indicator: CCI
      period: 14
    - indicator: DX
      period: 14
    - indicator: MFI
      period: 14
    - indicator: MOM
      period: 14
    - indicator: ROC
      period: 14
    - indicator: ROCP
      period: 14
    - indicator: ROCR
      period: 14
    - indicator: RSI
      period: 14
    - indicator: TRIX
      period: 14
    - indicator: WILLR
      period: 14
  macd:
    - fast_period: 12
      slow_period: 26
      signal_period: 9
      source: close
  stochastic:
    - fastk_period: 5
      slowk_period: 3
      slowk_matype: 0
      slowd_period: 3
      slowd_matype: 0
  cycle:
    - indicator: HT_DCPERIOD
      source: close
    - indicator: HT_DCPHASE
      source: close
    - indicator: HT_TRENDMODE
      source: close
  cdl_pattern:
    - pattern: CDL3STARSINSOUTH
    - pattern: CDLABANDONEDBABY
    - pattern: CDLCLOSINGMARUBOZU
    - pattern: CDLCOUNTERATTACK
    - pattern: CDLDARKCLOUDCOVER
    - pattern: CDLDOJI
    - pattern: CDLDOJISTAR
    - pattern: CDLDRAGONFLYDOJI
    - pattern: CDLENGULFING
    - pattern: CDLEVENINGDOJISTAR
    - pattern: CDLEVENINGSTAR
    - pattern: CDLGRAVESTONEDOJI
    - pattern: CDLHAMMER
    - pattern: CDLHANGINGMAN
    - pattern: CDLHARAMI
    - pattern: CDLINVERTEDHAMMER
    - pattern: CDLMARUBOZU
    - pattern: CDLMORNINGDOJISTAR
    - pattern: CDLMORNINGSTAR
    - pattern: CDLPIERCING
    - pattern: CDLSHOOTINGSTAR
    - pattern: CDLTAKURI
    - pattern: CDLTRISTAR
